### ISSUE TITLE
Make it possible to edit files when they were shared by public link [FIXES]

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#63]
When I'm sharing by public link, no matter file or folder, I want to be able to:
  - edit file in the OnlyOffice
  - upload a new file to a folder
  - remove a file from the folder
  - create a new version of the file

So at the very first iteration to not change a lot the screen with the sharing file options, we can along with the "Read" file permission, add the "Write" one
<img width="590" alt="image" src="https://github.com/linagora/TDrive/assets/14924963/00b40e8f-7842-4969-a8aa-4ad17b2c5f25">

**Comment by RomaricMourgues** [comment]
If I'm not here to do it:
- We need first to change `tdrive/backend/node/src/services/files/web/routes.ts` POST and DELETE endpoints because they do not check the tdrive parent folders access and are open to anyone in the company (so also not great for guests). Change the request body to get the drive_file id / drive_file_version id etc then check this drive parent access using the `tdrive/backend/node/src/services/documents/services/access-check.ts` method
- Change also in the frontend
- The applications like OnlyOffice still use the old routes without sending the new request body containing the drive_file and so on, there is something to do here (careful Onlyoffice code is also used for Twake), may be just let the applications do as they wish without checking drive_file.

**Comment by RomaricMourgues** [comment]
Part 1 merged, part 2 todo:
- Preview/editing with onlyoffice doesn't work on shared links in fact because /application endpoint gets blocked as I'm not connected (update all endpoints to use the shared links concept ?)
- Currently no security on uploading files, still using the old endpoint in "files" services (todo: see my comment on https://github.com/linagora/TDrive/issues/63)

**Comment by RomaricMourgues** [comment]
Tests on QA a lot is not working:
- Unable to drag drop file in shared link view nothing happens
- Unable to upload file at all, got a 401
- When going back to "root" shared directory it asks again to type the password
- Unable to add version, nothing is happening

**Comment by RomaricMourgues** [comment]
Still some issues on the frontend:
- If password is needed but a JWT is already set, the second time I try to get a token and get an error (because I didn't enter a password the second time) I should ignore the already existing JWT in shared view
- OnlyOffice edition works, but the first time application endpoint is called before the anonymous JWT is obtained, resulting in non detection of onlyoffice
