### ISSUE TITLE
Database connection error 

### ISSUE THREAD

**Issue by zaheer-Khan3260** [linagora/twake-drive-legacy#707]
**Describe the bug**
While clone and set the project locally in my machine it through a error: failed to connect database. I followed all the instruction to clone and set up the project locally.

**To Reproduce**
Clone the repositry into your local system follow all the step that is mantion in readme file. then Start the backend using command 
" yarn dev " or "npm run dev". you will see the error. And don't forget to start the docker before running backend.

**Screenshots**

![Screenshot 2024-10-24 170223](https://github.com/user-attachments/assets/cf7a84bb-3d44-49e6-badd-0d38c966ae34)

**Comment by ericlinagora** [comment]
You need to use docker compose, the readme might be out of date, but it's trying to connect to host "mongo", which would be valid inside the docker compose containers, so use that for the backend too. You can take a look here for what's actually used, with apologies if the readme was misleading: https://github.com/linagora/twake-drive/blob/main/.github/workflows/build.yml#L65 . To run locally (eg with yarn dev) you'll need to setup the environment variables from https://github.com/linagora/twake-drive/blob/main/tdrive/backend/node/config/custom-environment-variables.json so that it can connect to however you're starting the dbs etc.

**Comment by zaheer-Khan3260** [comment]
Hey @ericlinagora  i used all of these but it still through the same error. 
i explain what i do step by step :
1. firstly I run the commande "docker-compose up -d" to run the mongo container backend. after this it again through the same error message.
2. i initialize the env variable in this " https://github.com/linagora/twake-drive/blob/main/tdrive/backend/node/config/custom-environment-variables.json" file according you mantion in the readme file. 
3. i start the frontend using command npm run dev:start 
4. I start the beckend using "npm run dev" without giving the env variable in the commande. but it show the same error.
5. I again start the backend using "npm run dev" with the env variable that you suggest in the readme file. but again the same error.

can you help me with this please??

**Comment by ericlinagora** [comment]
The simplest solution is to just run back and front both in containers also, within the docker compose. If you look at the CI commands from github actions that I linked to, they setup a fully functioning set, including specifying appropriate env vars. If you wish to run the back locally (and not in a container), you will need to set similar env vars as in the compose yaml file, but adapted to point to endpoints where mongo and friends can be contacted. If you run only mongo in only docker, and the ports are published, then your mongo host for the backend will be localhost.

**Comment by zaheer-Khan3260** [comment]
Thanks for your help now i am running both front and back using docker.
