### ISSUE TITLE
[Bug] Can't download folders

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-drive-legacy#742]
vv1.0.5rc6, drive.stg.lin-saas.com, Safari

1. Upload a folder 
2. Try downloading it
3. Error 

https://github.com/user-attachments/assets/40efafa1-92e2-4957-8e05-339cae960839

**Comment by MontaGhanmy** [comment]
Currently, downloads in Safari are failing because the browser blocks new tabs triggered by the download process.

**Potential Solutions:**

- Initiate the download within the same page instead of opening a new tab.
- Implement a delay (e.g., setTimeout) to see if Safari allows the action.
- Use an iframe?
- Display a warning message asking users to change their settings to allow new tab downloads.
